Api endpoint examples
ConsenSys/doc.web3signer pull request #105
Opened 2022-01-11 18:56 UTC by rolandtyler

## Describe the change
Add examples and clarification using the API endpoints.

## Issue fixed
Fixes #104 

## Impacted parts 

### For content changes

- [x] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2022-01-24 05:24 UTC, jframe commented on docs/Reference/Rest.md
> +
Think we should add curl command to these examples so people can copy and paste

2022-01-24 05:24 UTC, jframe commented on docs/Reference/Rest.md
> +### `/eth/v1/keystores`
This should be /api/v1/eth1/publicKeys

2022-01-24 05:24 UTC, jframe commented on docs/Reference/Rest.md
> +
The data to be signed needs to be specified in the request body. Giving an example for this might be bit tricky there are a lot possibilities.

2022-02-02 05:54 UTC, jframe commented on docs/Reference/Rest.md
> +
Think we should mention that these methods require enabling using the --key-manager-api-enabled command line when using eth2 mode.

2022-02-02 23:39 UTC, jframe approved these changes

2022-02-03 21:50 UTC, bgravenorst requested changes
@rolandtyler, the Key Manager content is missing some conceptual information. For example, what/when/why use the Key Manager APIs (unless It's being addressed in a seperate PR). We could then include using the key manager APIs in a How to topic. 

Also, to avoid duplication, we should add any missing information directly in the API documentation. This will require you to update the OpenAPI comments in the codebase. For example the extra info you added for reload/upcheck should be added to the code. I can show you how to do this (or @NicolasMassart) if I'm unavailable.

Let me know if you want to discuss.

2022-02-09 00:17 UTC, bgravenorst requested changes
See feedback. Let me know if we need to discuss any of them, or need more clarity.

2022-02-09 00:17 UTC, bgravenorst commented on docs/Reference/Rest.md
> +### `/reload`
Not sure we should be hiding this information in the reference section. For example would this make more sense in the "Use signing keys" topic.

Maybe we could mention that you can reload signing keys if new keys were added to a validator (or set of validators), and then link off to the API docs. Don't think we need to duplicate it here.

2022-02-09 00:17 UTC, bgravenorst commented on docs/Reference/Rest.md
> +### `/upcheck`
I would move this content to the "Start Web3Signer" topic. Perhaps under a subheading like, "Confirm Web3Signer is running.

We do something similar for EthSigner, see: https://docs.ethsigner.pegasys.tech/en/latest/Tutorials/Start-EthSigner/#confirm-ethsigner-is-up

2022-02-09 00:17 UTC, bgravenorst commented on docs/Reference/Rest.md
> +Enable the key manager API by running Web3Signer with the [`--key-manager-api-enabled` subcommand](CLI/CLI-Subcommands.md#key-manager-api-enabled).
If you want, we could include the Request and Results in the topic. But I don't think we need to duplicate parameter descriptions if it's already in the API docs. We should link to it whenever possible.

2022-02-09 22:46 UTC, bgravenorst approved these changes
Minor comment. Otherwise lgtm

2022-02-09 22:46 UTC, bgravenorst commented on docs/Reference/Rest.md
> +## Key manager API
Can probably delete this.

2022-02-10 16:48 UTC, merged